### ISSUE TITLE
How to show legend at pie chart?

### ISSUE THREAD

**Issue by baur** [mahrus-kh/crud-php-mysql-pdo-modal-bootstrap#1]
Hi, 
How to show legend at charts, especially at pie chart?
thanks!

**Comment by baur** [comment]
& how to show marks

**Comment by ghost** [comment]
Do you mean "How to display data from database to pie chart ? "
It's using chart.js plugins, in file addfile/grafik/chart-siswa.js
.
mark using "id"

**Comment by baur** [comment]
no, charts works fine
but i'd like to show chart legend 
![image](https://user-images.githubusercontent.com/2898361/27899071-8c8ce4f8-624a-11e7-9a6a-70abae150bc8.png)
and marks
![image](https://user-images.githubusercontent.com/2898361/27899312-82088216-624b-11e7-9aa5-ac82d07b083f.png)

**Comment by ghost** [comment]
i have never used it, i'm sorry.. I'm just still learning
but it's about just view, you can follow this tutorial [LevelUpTuts](https://youtu.be/U8x6_2InIOw). 
Lots of tutorials there. 
If you succeed, you can share with others, especially me
