### ISSUE TITLE
Offline mode: Timed_out and 404

### ISSUE THREAD

**Issue by baur** [mahrus-kh/crud-php-mysql-pdo-modal-bootstrap#3]
errors at offline mode
![image](https://user-images.githubusercontent.com/2898361/27899451-1e6ce480-624c-11e7-9ac5-b4e2ce2b67a2.png)
app loads after 30 sec or more time

**Comment by ghost** [comment]
Yes,,
because of that file (icheck.js) was taken online.. but in this app don't use it, you can delete the code line.. 
that is my mistake
